create table public.player_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '旅人' check (char_length(display_name) between 1 and 40),
  level integer not null default 1 check (level >= 1),
  experience integer not null default 0 check (experience >= 0),
  stamina integer not null default 100 check (stamina between 0 and 100),
  focus integer not null default 100 check (focus between 0 and 100),
  willpower integer not null default 100 check (willpower between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.quests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 80),
  content text not null default '',
  difficulty text not null default 'normal' check (difficulty in ('easy','normal','hard')),
  exp_reward integer not null default 20 check (exp_reward >= 0),
  stamina_cost integer not null default 0 check (stamina_cost >= 0),
  focus_cost integer not null default 0 check (focus_cost >= 0),
  willpower_cost integer not null default 0 check (willpower_cost >= 0),
  deadline timestamptz,
  reward text not null default '',
  status text not null default 'pending' check (status in ('pending','active','completed')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.journal_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 80),
  body text not null check (char_length(body) between 1 and 10000),
  created_at timestamptz not null default now()
);

create index quests_user_sort_idx on public.quests (user_id, status, sort_order, created_at desc);
create index journal_entries_user_created_idx on public.journal_entries (user_id, created_at desc);

alter table public.player_profiles enable row level security;
alter table public.quests enable row level security;
alter table public.journal_entries enable row level security;

grant select, insert, update, delete on public.player_profiles to authenticated;
grant select, insert, update, delete on public.quests to authenticated;
grant usage, select on sequence public.quests_id_seq to authenticated;
grant select, insert, delete on public.journal_entries to authenticated;
grant usage, select on sequence public.journal_entries_id_seq to authenticated;

create policy "players_select_own_profile" on public.player_profiles for select to authenticated using ((select auth.uid()) = user_id);
create policy "players_insert_own_profile" on public.player_profiles for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "players_update_own_profile" on public.player_profiles for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "players_delete_own_profile" on public.player_profiles for delete to authenticated using ((select auth.uid()) = user_id);
create policy "players_select_own_quests" on public.quests for select to authenticated using ((select auth.uid()) = user_id);
create policy "players_insert_own_quests" on public.quests for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "players_update_own_quests" on public.quests for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "players_delete_own_quests" on public.quests for delete to authenticated using ((select auth.uid()) = user_id);
create policy "players_select_own_journals" on public.journal_entries for select to authenticated using ((select auth.uid()) = user_id);
create policy "players_insert_own_journals" on public.journal_entries for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "players_delete_own_journals" on public.journal_entries for delete to authenticated using ((select auth.uid()) = user_id);
